config/routes.rb
Rails.application.routes.draw do
  resources :contactos
  devise_for :users
  root to: 'contactos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contacto.rb
class Contacto < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
  before_action :set_contacto, only: %i[ show edit update destroy ]

  # GET /contactos or /contactos.json
  def index
    @contactos = Contacto.all
  end

  # GET /contactos/1 or /contactos/1.json
  def show
  end

  # GET /contactos/new
  def new
    @contacto = Contacto.new
  end

  # GET /contactos/1/edit
  def edit
  end

  # POST /contactos or /contactos.json
  def create
    @contacto = Contacto.new(contacto_params)

    respond_to do |format|
      if @contacto.save
        format.html { redirect_to contacto_url(@contacto), notice: "Contacto was successfully created." }
        format.json { render :show, status: :created, location: @contacto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contactos/1 or /contactos/1.json
  def update
    respond_to do |format|
      if @contacto.update(contacto_params)
        format.html { redirect_to contacto_url(@contacto), notice: "Contacto was successfully updated." }
        format.json { render :show, status: :ok, location: @contacto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactos/1 or /contactos/1.json
  def destroy
    @contacto.destroy

    respond_to do |format|
      format.html { redirect_to contactos_url, notice: "Contacto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contacto
      @contacto = Contacto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contacto_params
      params.require(:contacto).permit(:nombre, :apellido, :telefono, :correo, :immo, :tipo, :detalle)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contactos/_form.html.erb
<%= simple_form_for(@contacto) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :apellido %>
    <%= f.input :telefono %>
    <%= f.input :correo %>
    <%= f.input :immo %>
    <%= f.input :tipo %>
    <%= f.input :detalle %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contactos/edit.html.erb
<h1>Editing Contacto</h1>

<%= render 'form', contacto: @contacto %>

<%= link_to 'Show', @contacto %> |
<%= link_to 'Back', contactos_path %>

app/views/contactos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contactos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Telefono</th>
      <th>Correo</th>
      <th>Immo</th>
      <th>Tipo</th>
      <th>Detalle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contactos.each do |contacto| %>
      <tr>
        <td><%= contacto.nombre %></td>
        <td><%= contacto.apellido %></td>
        <td><%= contacto.telefono %></td>
        <td><%= contacto.correo %></td>
        <td><%= contacto.immo %></td>
        <td><%= contacto.tipo %></td>
        <td><%= contacto.detalle %></td>
        <td><%= link_to 'Show', contacto %></td>
        <td><%= link_to 'Edit', edit_contacto_path(contacto) %></td>
        <td><%= link_to 'Destroy', contacto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contacto', new_contacto_path %>

app/views/contactos/new.html.erb
<h1>New Contacto</h1>

<%= render 'form', contacto: @contacto %>

<%= link_to 'Back', contactos_path %>

app/views/contactos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @contacto.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @contacto.apellido %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @contacto.telefono %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @contacto.correo %>
</p>

<p>
  <strong>Immo:</strong>
  <%= @contacto.immo %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @contacto.tipo %>
</p>

<p>
  <strong>Detalle:</strong>
  <%= @contacto.detalle %>
</p>

<%= link_to 'Edit', edit_contacto_path(@contacto) %> |
<%= link_to 'Back', contactos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>REVALORA</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>